POST http://localhost:3000/jobs
Content-Type: application/json

{
    "jobTitle": "Scopper",
    "company": "Scopper International",
    "jobLink": "www.scupper.com",
    "status": "offer",
    "resume": "my-cv-scupper",
    "coverLetter": "Scupper cover letter"
}

### Get all applications available
GET http://localhost:3000/jobs

### get single applications with id
GET http://localhost:3000/jobs/69bbe86ec5ff540d8497267c

### edit job application with id
PUT http://localhost:3000/jobs/69bc038aff377a6fbcec8960
Content-Type: application/json

{
    "jobTitle": "Scopper Operator",
    "company": "Scopper Limited",
    "jobLink": "www.scopper.co.ng",
    "status": "rejected",
    "resume": "my-cv-scopper",
    "coverLetter": ""
}

### Delete job application
DELETE http://localhost:3000/jobs/69bbe988c5ff540d8497267e