POST http://localhost:3000/jobs
Content-Type: application/json
Authorization: Bearer

{
    "jobTitle": "Frontend Developer",
    "company": "Corousel Digital Agency",
    "jobLink": "www.carousel.com",
    "status": "offer",
    "resume": "my-cv-caros",
    "coverLetter": "Carousel cover letter"
}

### Get all applications available
GET http://localhost:3000/jobs
Authorization: Bearer 

### get single applications with id
GET http://localhost:3000/jobs/69c571235b5e48820e230c0b
Authorization: Bearer 

### edit job application with id
PUT http://localhost:3000/jobs/69c571235b5e48820e230c0b
Content-Type: application/json
Authorization: Bearer 

{
    "jobTitle": "Frontend Developer (Reactjs)",
    "company": "Corousel Digital Agency",
    "jobLink": "www.carousel.com",
    "status": "offer",
    "resume": "my-cv-caros",
    "coverLetter": "Carousel cover letter"
}

### Delete job application
DELETE http://localhost:3000/jobs/69c556d55ebbb207c1bd7d5e
Authorization: Bearer 


### Get all users available
GET http://localhost:3000/users
Authorization: Bearer 

### Create user
POST http://localhost:3000/users/
Content-Type: application/json
Authorization: Bearer 

{
    "name": "Paul Dawson",
    "email": "dawson@gmail.com",
    "password": "123456"
}

### Get single user
GET http://localhost:3000/users/me
Authorization: Bearer 


### Edit a user
PUT http://localhost:3000/users/
Content-Type: application/json
Authorization: Bearer 

{
    "name": "Paul Dawson Grnds",
    "email": "dawson@gmail.com",
    "password": "1234567"
}


### Delete a user
DELETE http://localhost:3000/users/
Authorization: Bearer 


### post to login a user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "flavor@gmail.com",
    "password": "123456"
}


### get user
GET http://localhost:3000/auth/
Authorization: Bearer 


### logout
POST http://localhost:3000/auth/logout
Authorization: Bearer 
